name: DiaWatcher
version: 1.0
main: io.github.mcrtin.diaWatcher.Main
api-version: 1.16
commands:
   sendDiaFeedback:
      description: toggle whether the diatransactions should print feedback to you
      permission: DiaWatcher.sendDiaFeedback